version = "3.7.17"
runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.defnSite = 2
indent.callSite = 2

align.preset = none
lineEndings = unix

docstrings.style = Asterisk

newlines.source = keep
newlines.topLevelStatements = [before,after]
